### ISSUE TITLE
Error when running inserts from console

### ISSUE THREAD

**Issue by maxxer** [bupy7/yii2-activerecord-history#2]
When running AR creation from console commands the behavior returns error

```
Exception: Calling unknown method: yii\console\Application::getSession() (/home/maxxer/vendor/yiisoft/yii2/base/Component.php:285)
#0 /home/maxxer/vendor/yiisoft/yii2/web/User.php(657): yii\base\Component->__call('getSession', Array)
#1 /home/maxxer/vendor/yiisoft/yii2/web/User.php(188): yii\web\User->renewAuthStatus()
#2 /home/maxxer/vendor/yiisoft/yii2/web/User.php(350): yii\web\User->getIdentity()
#3 /home/maxxer/vendor/yiisoft/yii2/base/Component.php(130): yii\web\User->getId()
#4 /home/maxxer/vendor/bupy7/yii2-activerecord-history/behaviors/History.php(194): yii\base\Component->__get('id')
#5 /home/maxxer/vendor/bupy7/yii2-activerecord-history/behaviors/History.php(105): bupy7\activerecord\history\behaviors\History->getCreatedBy()
#6 [internal function]: bupy7\activerecord\history\behaviors\History->saveHistory(Object(yii\db\AfterSaveEvent))
```

**Comment by maxxer** [comment]
Possible fix: 

``` patch
11:50 $ diff -Naur vendor/bupy7/yii2-activerecord-history/behaviors/History_orig.php vendor/bupy7/yii2-activerecord-history/behaviors/History.php --- vendor/bupy7/yii2-activerecord-history/behaviors/History_orig.php 2016-10-05 11:49:56.683069585 +0200
+++ vendor/bupy7/yii2-activerecord-history/behaviors/History.php    2016-10-05 11:04:15.699624100 +0200
@@ -100,6 +100,8 @@
      */
     public function saveHistory(Event $event)
     {   
+        if(is_a(Yii::$app,'yii\console\Application'))
+            return;
         $rowId = $this->getRowId();
         $tableName = $this->getTableName();
         $createdBy = $this->getCreatedBy();

```

**Comment by bupy7** [comment]
@maxxer No. Need ID of an user. This is a mandatory requirement. You need authenticated an user in console or don't use history.

**Comment by maxxer** [comment]
The same happens with Blameable Behavior [they say](https://github.com/yiisoft/yii2/issues/5434), but they allow to set the value to be used, in case `Yii::$app->user` is not available.

**Comment by maxxer** [comment]
I should create a fake console user component implementing \yii\web\User that must return something to the ->id getter?

**Comment by bupy7** [comment]
Make a service user and run below code before some action:

``` php
$identity = \app\models\User::findIdentity('<service_user_id>');
if ($identity === null) {
   throw new ForbiddenHttpException;
}
\Yii::$app->user->setIdentity($identity); 
```

Set custom user will be to future functional.

**Comment by maxxer** [comment]
ok thanks...
